"""create knowledge table

Revision ID: 432cf92453e4
Revises: e5e2a77d2a9d
Create Date: 2026-09-21 16:09:48.714209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432cf92453e4'
down_revision: Union[str, Sequence[str], None] = 'e5e2a77d2a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("session_id", sa.Integer(), sa.ForeignKey("sessions.id"), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    )
    op.create_index(op.f("ix_knowledge_session_id"), "knowledge", ["session_id"], unique=False)
    op.create_index(op.f("ix_knowledge_status"), "knowledge", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_status"), table_name="knowledge")
    op.drop_index(op.f("ix_knowledge_session_id"), table_name="knowledge")
    op.drop_table("knowledge")
    # ### end Alembic commands ###
